files:
  - source: /src/Shared/HandyControl_Shared/Properties/Langs/Lang.en.resx
    translation: /src/Shared/HandyControl_Shared/Properties/Langs/Lang.%locale%.resx
  - source: /src/Shared/HandyControlDemo_Shared/Properties/Langs/Lang.en.resx
    translation: /src/Shared/HandyControlDemo_Shared/Properties/Langs/Lang.%locale%.resx
